INSERT INTO species (species_id, species_name) VALUES
(1, 'Dog'),
(2, 'Cat'),
(3, 'Rabbit'),
(4, 'Bird'),
(5, 'Guinea Pig');

INSERT INTO breeds (breed_id, species_id, breed_name) VALUES
(1, 1, 'Labrador Retriever'),
(2, 1, 'Border Collie'),
(3, 1, 'Golden Retriever'),
(4, 1, 'German Shepherd'),
(5, 1, 'Staffordshire Bull Terrier'),
(6, 1, 'Jack Russell Terrier'),
(7, 2, 'Domestic Short Hair'),
(8, 2, 'Domestic Medium Hair'),
(9, 2, 'Domestic Long Hair'),
(10, 2, 'Ragdoll'),
(11, 2, 'Siamese'),
(12, 2, 'British Shorthair'),
(13, 3, 'Netherland Dwarf'),
(14, 3, 'Mini Lop'),
(15, 3, 'Dutch Rabbit'),
(16, 4, 'Cockatiel'),
(17, 4, 'Budgerigar');

INSERT INTO foster_carers (foster_carer_id, first_name, last_name, email, phone, suburb, preferred_animal_type, capacity, status, notes) VALUES
(1, 'Sarah', 'Jenkins', 'sarah.j@example.com', '0412345001', 'Caulfield', 'Dog', 2, 'Active', 'Has a secure backyard with high fences.'),
(2, 'Michael', 'Chang', 'm.chang@example.com', '0412345002', 'Clayton', 'Cat', 3, 'Active', 'Experienced with nursing kittens.'),
(3, 'Jessica', 'Taylor', 'jtaylor@example.com', '0412345003', 'St Kilda', 'Dog', 1, 'Active', 'Works from home full time.'),
(4, 'David', 'Wilson', 'david.w@example.com', '0412345004', 'Richmond', 'Cat', 2, 'Active', 'Quiet apartment with indoor cat netting.'),
(5, 'Emily', 'Brown', 'emily.b@example.com', '0412345005', 'Glen Waverley', 'Dog', 2, 'Active', 'Experienced dog trainer and handler.'),
(6, 'James', 'Anderson', 'j.anderson@example.com', '0412345006', 'South Yarra', 'Rabbit', 2, 'Active', 'Dedicated rabbit enclosure indoors.'),
(7, 'Chloe', 'Martin', 'chloe.m@example.com', '0412345007', 'Malvern', 'Dog', 1, 'Active', 'Lives near local dog parks.'),
(8, 'Daniel', 'White', 'dwhite@example.com', '0412345008', 'Oakleigh', 'Cat', 2, 'Inactive', 'Taking a temporary break until next month.'),
(9, 'Olivia', 'Harris', 'olivia.h@example.com', '0412345009', 'Carnegie', 'Dog', 3, 'Active', 'Large farm-style property, highly experienced.'),
(10, 'Matthew', 'Clark', 'mclark@example.com', '0412345010', 'Hawthorn', 'Cat', 1, 'Active', 'Prefers senior cats needing a quiet space.'),
(11, 'Sophia', 'Lewis', 'sophia.l@example.com', '0412345011', 'Box Hill', 'Rabbit', 2, 'Active', 'Experienced with rescue bunnies.'),
(12, 'Andrew', 'Walker', 'a.walker@example.com', '0412345012', 'Brighton', 'Dog', 2, 'Active', 'Experienced with active medium/large dogs.'),
(13, 'Hannah', 'Hall', 'hhall@example.com', '0412345013', 'Prahran', 'Cat', 2, 'Active', 'No other pets, perfect for single cat stays.'),
(14, 'Joshua', 'Allen', 'josh.allen@example.com', '0412345014', 'Bentleigh', 'Dog', 1, 'Inactive', 'Renovating home, unavailable until December.'),
(15, 'Grace', 'Young', 'grace.y@example.com', '0412345015', 'Camberwell', 'Bird', 4, 'Active', 'Spacious aviary setup available.');

INSERT INTO animals (animal_id, name, breed_id, sex, desexed, date_of_birth, date_admitted, description, medical_notes, status, profile_image, foster_carer_id) VALUES
(1, 'Max', 1, 'Male', TRUE, '2022-03-15', '2026-05-10', 'Max is a friendly and energetic Labrador who loves fetch and playing with water.', 'Up to date with all vaccinations. Microchipped.', 'Available for adoption', 'max_labrador.jpg', 1),
(2, 'Luna', 7, 'Female', TRUE, '2023-06-20', '2026-06-01', 'Luna is an affectionate domestic short hair cat who enjoys cuddles and sunny spots.', 'Sterilised, treated for fleas and worms.', 'Available for adoption', 'luna_cat.jpg', 2),
(3, 'Charlie', 2, 'Male', TRUE, '2021-11-05', '2026-04-18', 'Charlie is a smart Border Collie who thrives with puzzle toys and active outdoor adventures.', 'Requires daily joint supplements.', 'In care', 'charlie_collie.jpg', 5),
(4, 'Bella', 10, 'Female', TRUE, '2024-01-10', '2026-07-02', 'Bella is a gentle Ragdoll with bright blue eyes. Perfect lap companion.', 'Healthy, clear vet check on admission.', 'Available for adoption', 'bella_ragdoll.jpg', 4),
(5, 'Rocky', 5, 'Male', TRUE, '2020-08-12', '2026-03-22', 'Rocky is a sweet-natured Staffy mix who gets along well with calm dogs.', 'Mild skin allergy managed by diet.', 'Adoption pending', 'rocky_staffy.jpg', 9),
(6, 'Milo', 11, 'Male', TRUE, '2023-09-01', '2026-06-15', 'Milo is a vocal and curious Siamese cat who loves human interaction.', 'Vaccinated and wormed.', 'Adopted', 'milo_siamese.jpg', NULL),
(7, 'Daisy', 3, 'Female', TRUE, '2022-07-30', '2026-05-20', 'Daisy is a joyful Golden Retriever who is gentle with kids and other pets.', 'All core vaccinations up to date.', 'Available for adoption', 'daisy_retriever.jpg', 12),
(8, 'Oliver', 12, 'Male', TRUE, '2022-02-14', '2026-06-10', 'Oliver is a calm British Shorthair who loves quiet environments and window watching.', 'Desexed and microchipped.', 'Available for adoption', 'oliver_cat.jpg', 2),
(9, 'Coco', 14, 'Female', FALSE, '2024-05-01', '2026-07-15', 'Coco is a miniature lop rabbit who is litter trained and loves fresh greens.', 'Scheduled for desexing next month.', 'In care', 'coco_rabbit.jpg', 6),
(10, 'Bailey', 6, 'Male', TRUE, '2021-04-19', '2026-04-05', 'Bailey is a lively Jack Russell Terrier with great agility and playful enthusiasm.', 'Fully healthy and energetic.', 'Available for adoption', 'bailey_terrier.jpg', 3),
(11, 'Simba', 8, 'Male', TRUE, '2023-12-01', '2026-06-25', 'Simba is a ginger medium hair cat who loves chasing laser pointers.', 'Routine deworming completed.', 'Available for adoption', 'simba_cat.jpg', 13),
(12, 'Ruby', 4, 'Female', TRUE, '2022-10-10', '2026-05-30', 'Ruby is an alert and loyal German Shepherd looking for an active handler.', 'Hip score checked, excellent condition.', 'Adoption pending', 'ruby_shepherd.jpg', 5),
(13, 'Pepper', 13, 'Male', TRUE, '2023-08-15', '2026-07-01', 'Pepper is a small Netherland Dwarf bunny with a big curious personality.', 'Vaccinated for Calicivirus.', 'Available for adoption', 'pepper_rabbit.jpg', 11),
(14, 'Sunny', 16, 'Male', FALSE, '2024-02-20', '2026-07-18', 'Sunny is a cheerful Cockatiel who whistles tunes and enjoys head scratches.', 'Wings unclipped, excellent feather condition.', 'Available for adoption', 'sunny_bird.jpg', 15),
(15, 'Chloe', 9, 'Female', TRUE, '2021-06-08', '2026-04-29', 'Chloe is a fluffy long hair cat who needs regular grooming and lots of affection.', 'Requires weekly coat brushing.', 'In care', 'chloe_cat.jpg', 10),
(16, 'Buster', 1, 'Male', TRUE, '2019-12-05', '2026-03-01', 'Buster is a relaxed senior Labrador looking for a quiet retirement home.', 'Mild arthritis, on daily joint support.', 'Adopted', 'buster_lab.jpg', NULL);

INSERT INTO partner_organisations (organisation_id, name, organisation_type, contact_person, email, phone, address, website, notes) VALUES
(1, 'Caulfield Veterinary Hospital', 'Veterinary Clinic', 'Dr. Robert Smith', 'admin@caulfieldvet.com.au', '0395091234', '120 Glenhuntly Rd, Caulfield VIC', 'https://www.caulfieldvet.com.au', 'Offers discounted desexing and emergency triage.'),
(2, 'Clayton Animal Hospital', 'Veterinary Clinic', 'Dr. Laura Evans', 'info@claytonanimalvet.com.au', '0395445678', '256 Clayton Rd, Clayton VIC', 'https://www.claytonanimalvet.com.au', 'Primary clinic for routine microchipping and vaccinations.'),
(3, 'Melbourne Pet Nutrition Co', 'Pet Supply Partner', 'Mark Henderson', 'contact@melbpetnutrition.com.au', '0398223344', '45 Commercial Rd, Prahran VIC', 'https://www.melbpetnutrition.com.au', 'Sponsors dry kibble for foster dogs and cats.'),
(4, 'St Kilda 24/7 Emergency Vet', 'Animal Hospital', 'Dr. Fiona Clarke', 'support@stkildavet247.com.au', '0395348899', '18 St Kilda Rd, St Kilda VIC', 'https://www.stkildavet247.com.au', 'Handles after-hours veterinary emergencies.'),
(5, 'Richmond Animal Welfare League', 'Community Partner', 'Simon Davis', 'info@richmondwelfare.org.au', '0394281122', '88 Bridge Rd, Richmond VIC', 'https://www.richmondwelfare.org.au', 'Assists with community outreach and adoption days.'),
(6, 'Glen Eira Veterinary Clinic', 'Veterinary Clinic', 'Dr. Amanda Green', 'enquiries@gleneiravet.com.au', '0395782211', '72 Koornang Rd, Carnegie VIC', 'https://www.gleneiravet.com.au', 'Specialised in feline health and dental care.'),
(7, 'Monash Pet Rehabilitation', 'Specialist Care', 'Kelly Wright', 'info@monashpetrehab.com.au', '0395627788', '14 Blackburn Rd, Glen Waverley VIC', 'https://www.monashpetrehab.com.au', 'Provides hydrotherapy and post-surgical rehab.'),
(8, 'South Yarra Vet Specialists', 'Specialist Clinic', 'Dr. Patrick Morris', 'reception@syvetspec.com.au', '0398279900', '310 Toorak Rd, South Yarra VIC', 'https://www.syvetspec.com.au', 'Orthopedic surgery and ultrasound diagnostics.'),
(9, 'Oakleigh Community Paws', 'Rescue Partner', 'Rachel Bell', 'rachel@oakleighpaws.org.au', '0395684455', '5 Atherton Rd, Oakleigh VIC', 'https://www.oakleighpaws.org.au', 'Coordinates local stray capture and surrender transport.'),
(10, 'Paws & Claws Grooming Studio', 'Grooming Partner', 'Jack Foster', 'studio@pawsandclaws.com.au', '0395213344', '150 Centre Rd, Bentleigh VIC', 'https://www.pawsandclaws.com.au', 'Provides complimentary grooming for rescue animals.'),
(11, 'Hawthorn Veterinary Centre', 'Veterinary Clinic', 'Dr. Brian King', 'hello@hawthornvet.com.au', '0398184422', '80 Glenferrie Rd, Hawthorn VIC', 'https://www.hawthornvet.com.au', 'Provides general wellness checks and flea treatments.'),
(12, 'Melbourne Rabbit Rescue Network', 'Specialist Partner', 'Alice Morgan', 'contact@melbrabbitrescue.org.au', '0398901177', '12 Station St, Box Hill VIC', 'https://www.melbrabbitrescue.org.au', 'Advisory and rehoming partner for small mammals.'),
(13, 'Bayside Animal Care Clinic', 'Veterinary Clinic', 'Dr. Nathan Scott', 'care@baysideanimal.com.au', '0395926633', '90 Church St, Brighton VIC', 'https://www.baysideanimal.com.au', 'Routine vaccinations and dental cleans.'),
(14, 'Camberwell Pet Essentials', 'Pet Supply Partner', 'Megan Turner', 'sales@camberwellpet.com.au', '0398825511', '400 Riversdale Rd, Camberwell VIC', 'https://www.camberwellpet.com.au', 'Donates bedding, crates, and leashes.'),
(15, 'Victoria Avian & Exotic Vet', 'Specialist Clinic', 'Dr. Henry Phillips', 'clinic@vicexoticvet.com.au', '0393806655', '22 Sydney Rd, Brunswick VIC', 'https://www.vicexoticvet.com.au', 'Exotic pet medicine, avian diagnostics, and surgery.');

INSERT INTO users (user_id, first_name, last_name, username, password, status) VALUES
(1, 'Emma', 'Wilson', 'emma.wilson', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(2, 'Sarah', 'Jenkins', 'sarah.j', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(3, 'Michael', 'Chang', 'michael.c', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(4, 'David', 'Miller', 'david.m', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(5, 'Jessica', 'Taylor', 'jessica.t', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(6, 'Daniel', 'Anderson', 'daniel.a', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(7, 'Emily', 'Brown', 'emily.b', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(8, 'James', 'Harris', 'james.h', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(9, 'Chloe', 'Martin', 'chloe.m', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(10, 'Matthew', 'Clark', 'matthew.c', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(11, 'Olivia', 'Walker', 'olivia.w', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(12, 'Andrew', 'Lewis', 'andrew.l', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(13, 'Sophia', 'Young', 'sophia.y', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Active'),
(14, 'Grace', 'Allen', 'grace.a', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Inactive'),
(15, 'Joshua', 'King', 'joshua.k', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Inactive');

INSERT INTO adoption_applications (application_id, animal_id, applicant_name, email, phone, suburb, housing_type, home_ownership, other_pets, reason_for_adoption, application_date, status) VALUES
(1, 1, 'Liam Campbell', 'liam.c@outlook.com', '0421111222', 'Caulfield', 'House with yard', 'Own', 'None', 'Looking for an energetic dog to accompany me on daily runs.', '2026-07-20 09:30:00', 'Approved'),
(2, 2, 'Sophie Turner', 'sophie.t@gmail.com', '0422222333', 'South Yarra', 'Apartment', 'Rent', '1 domestic cat', 'Want a gentle companion cat for my current cat.', '2026-07-21 14:15:00', 'Approved'),
(3, 4, 'Ethan Brooks', 'ethan.b@yahoo.com', '0423333444', 'Glen Waverley', 'Townhouse', 'Own', 'None', 'Adore Ragdoll cats and work from home.', '2026-07-22 11:00:00', 'Under review'),
(4, 5, 'Charlotte Davies', 'charlotte.d@gmail.com', '0424444555', 'Oakleigh', 'House with yard', 'Own', '1 older dog', 'Looking for a playful companion for our existing dog.', '2026-07-23 16:45:00', 'Approved'),
(5, 7, 'Noah Wilson', 'noah.w@hotmail.com', '0425555666', 'Brighton', 'House with yard', 'Own', 'None', 'Our family is looking for a gentle family dog.', '2026-07-24 10:20:00', 'New'),
(6, 8, 'Mia Johnson', 'mia.j@outlook.com', '0426666777', 'Malvern', 'Apartment', 'Rent', 'None', 'Looking for a calm, independent cat.', '2026-07-25 13:10:00', 'Under review'),
(7, 10, 'Lucas White', 'lucas.w@gmail.com', '0427777888', 'Hawthorn', 'Townhouse', 'Rent', 'None', 'Active lifestyle, looking for a loyal companion terrier.', '2026-07-26 15:50:00', 'New'),
(8, 11, 'Ava Robinson', 'ava.r@gmail.com', '0428888999', 'Prahran', 'Apartment', 'Own', 'None', 'Love ginger cats and have a quiet home.', '2026-07-27 12:05:00', 'New'),
(9, 12, 'Jack Thompson', 'jack.t@outlook.com', '0429999000', 'Clayton', 'House with yard', 'Own', 'None', 'Experienced with working dog breeds.', '2026-07-28 09:00:00', 'Under review'),
(10, 13, 'Amelia Harris', 'amelia.h@gmail.com', '0431111222', 'Box Hill', 'House with yard', 'Own', '2 rescue rabbits', 'Experienced rabbit owner with spacious rabbit enclosure.', '2026-07-29 17:30:00', 'New'),
(11, 14, 'William Martin', 'william.m@yahoo.com', '0432222333', 'Camberwell', 'House with yard', 'Own', 'None', 'Passionate about birds, have a dedicated aviary.', '2026-07-30 08:40:00', 'New'),
(12, 1, 'Ella Jackson', 'ella.j@gmail.com', '0433333444', 'Carnegie', 'House with yard', 'Rent', 'None', 'Want to give a loving rescue dog a forever home.', '2026-07-31 11:25:00', 'Rejected'),
(13, 2, 'Oliver Brown', 'oliver.b@outlook.com', '0434444555', 'St Kilda', 'Apartment', 'Rent', 'None', 'Looking for a friendly cat to keep me company.', '2026-08-01 14:00:00', 'Rejected'),
(14, 7, 'Isabella Smith', 'isabella.s@gmail.com', '0435555666', 'Bentleigh', 'House with yard', 'Own', 'None', 'Family dog companion for our children.', '2026-08-02 16:15:00', 'New'),
(15, 8, 'Henry Taylor', 'henry.t@yahoo.com', '0436666777', 'Richmond', 'Apartment', 'Own', 'None', 'Quiet household, looking for a calm indoor pet.', '2026-08-03 10:50:00', 'New');

INSERT INTO contact_messages (message_id, name, email, phone, message, submitted_date, replied) VALUES
(1, 'Alice Walker', 'alice.w@example.com', '0441111222', 'Hi, are you currently accepting new foster carers for medium dogs?', '2026-07-15 10:15:00', TRUE),
(2, 'Ben Hughes', 'ben.h@example.com', '0442222333', 'I would like to donate dog food and blankets. Where is your drop-off location?', '2026-07-16 11:30:00', TRUE),
(3, 'Caitlin Ross', 'caitlin.r@example.com', '0443333444', 'Is Max the Labrador good with young children?', '2026-07-18 14:20:00', TRUE),
(4, 'Dylan Scott', 'dylan.s@example.com', '0444444555', 'How long does the adoption screening process typically take?', '2026-07-20 09:00:00', TRUE),
(5, 'Elena Perry', 'elena.p@example.com', '0445555666', 'Can I visit the foster carer to meet Luna before submitting an application?', '2026-07-22 16:40:00', FALSE),
(6, 'Felix Cooper', 'felix.c@example.com', '0446666777', 'We represent a local pet store and want to organize an adoption weekend.', '2026-07-25 13:15:00', FALSE),
(7, 'Georgia Ward', 'georgia.w@example.com', '0447777888', 'Are all your cats desexed before going to their new homes?', '2026-07-26 15:00:00', TRUE),
(8, 'Harrison Reed', 'harrison.r@example.com', '0448888999', 'I found a stray kitten near Clayton station. Can SafePaws take it in?', '2026-07-28 08:30:00', TRUE),
(9, 'Ivy Morgan', 'ivy.m@example.com', '0449999000', 'What are the fencing requirements for adopting an active dog like Charlie?', '2026-07-29 12:45:00', FALSE),
(10, 'Julian Kelly', 'julian.k@example.com', '0451111222', 'Do you offer trial adoption periods for families with other pets?', '2026-07-30 17:10:00', FALSE),
(11, 'Klara Bennett', 'klara.b@example.com', '0452222333', 'Hi, is Pepper the rabbit bonded with any other rabbits?', '2026-08-01 09:50:00', FALSE),
(12, 'Leo Carter', 'leo.c@example.com', '0453333444', 'I sent an adoption application for Bella last week. Just following up.', '2026-08-02 11:20:00', FALSE),
(13, 'Maya Price', 'maya.p@example.com', '0454444555', 'Can international students apply to foster or adopt?', '2026-08-03 14:05:00', FALSE),
(14, 'Nicholas Wood', 'nick.w@example.com', '0455555666', 'Would love to volunteer with transportation on weekends.', '2026-08-04 10:30:00', FALSE),
(15, 'Olivia Barnes', 'olivia.b@example.com', '0456666777', 'Are veterinary records provided at the time of adoption handover?', '2026-08-05 16:00:00', FALSE);